// Generated by Wrangler by running `wrangler types`

interface Env {
	SECRET_KEY: "secret";
	APP_URL: "https://marula-open.dtegart78.workers.dev";
	R2: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
